name: DarkiWorld Plugin CI

# Déclencheurs du workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs du workflow
jobs:
  build:
    runs-on: ubuntu-latest  # Environnement d'exécution

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Java (JDK)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Version de Java requise
          distribution: 'temurin'  # Distribution de Java (OpenJDK)

      # Étape 3 : Donner les permissions d'exécution à gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Étape 4 : Construire le projet avec Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Étape 5 : Téléverser les artefacts de construction (fichier JAR)
      - name: Upload build artifacts
        if: success()  # Exécuter uniquement si la construction réussit
        uses: actions/upload-artifact@v3
        with:
          name: DarkiWorld-Plugin
          path: build/libs/*.jar  # Chemin vers le fichier JAR généré
