name: Build DarkiWorld Plugin

     on:
       push:
         branches:
           - main  # Déclenche le workflow lors d'un push sur la branche main
       pull_request:
         branches:
           - main  # Déclenche le workflow lors d'une pull request sur la branche main

     jobs:
       build:
         runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu

         steps:
           - name: Checkout code
             uses: actions/checkout@v3  # Télécharge le code du dépôt

           - name: Set up JDK 17
             uses: actions/setup-java@v3
             with:
               java-version: '17'  # Utilise Java 17
               distribution: 'temurin'

           - name: Grant execute permission for gradlew
             run: chmod +x gradlew  # Rend le script gradlew exécutable

           - name: Build with Gradle
             run: ./gradlew build  # Compile le projet avec Gradle

           - name: Upload artifact
             uses: actions/upload-artifact@v3
             with:
               name: DarkiWorldPlugin
               path: build/libs/*.jar  # Téléverse le fichier .jar généré
